version: '2.4'

services:
  web:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment: 
      - FLASK_SERVER_ADDR=backend:9091
      - FRONT_SERVER_ADDR=front:4200
      - ML_SERVER_ADDR=ml:6000

    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - mynetwork

  front:
    build:
      context: safer-webapp
      target: builder
    ports:
      - "4200:4200"
    volumes:
      - ./safer-webapp:/project
      - /project/node_modules

  backend:
    build:
      context: safer-ws
      target: builder
    stop_signal: SIGINT
    ports:
      - 9091:9091
      - 8089:8089

    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./safer-ws:/src
    depends_on:
      -  mongodb
    networks:
      - mynetwork
    mem_limit: 16G



  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-scripts:/docker-entrypoint-initdb.d
      - ./mongodb/csv:/csv
    networks:
      - mynetwork

  ml:
    build:
      context: safer-ml
    stop_signal: SIGINT
    ports:
      - 6000:6000
    environment:
      - FLASK_ML_SERVER_PORT=6000
    volumes:
      - ./safer-ml:/src
    networks:
      - mynetwork

volumes:
  mongodb_data:

networks:
  mynetwork:

